services:
  api-service:
    container_name: api-container-1
    build:
      context: /.
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8080:80'
    networks:
      - backend

# chạy với nhiều service khác nhau
#  api-service-test:  # tên service này không đượcc trùng nhau
#    container_name: api-container-2
#    image: api-image-sample
#    ports:
#      - '8081:80'
#    networks:
#      - backend


networks:
  backend:
    driver: bridge # mạng public