  spring:
    config:
      activate:
        on-profile: dev
    datasource:
      url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
      username: ${POSTGRES_USER:postgres}
      password: ${POSTGRES_PASSWORD:123456}
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
      hibernate:
        ddl-auto: none

  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true
  openapi:
    service:
      title: ${API_TITLE:DUMMY-API-TITLE}
      version: v1.0.0
      description: Mota API service
      serverUrl: http://localhost:${server.port}
      serverName: server dev
      api-docs: api-service

#  ${API_TITLE:DUMMY-API-TITLE}