server:
  port: 80
spring:
  application:
    name: spring-boot-sample-code-app-yml
  profiles:
    active: @spring.profiles.active@ # truyền giá trị muốn đóng gói với môi trường qua tham sô @<key>@ (dev, test, prod)

# Health check
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      probes:
        enabled: true
  health: # config for EKS
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  prometheus:
    metrics:
      export:
        step: 5s
        enabled: true

  # Logging
  logging:
    level:
      root: INFO
      web: OFF
      org.springframework: INFO
      org.apache: OFF
      kafka: OFF
